# Generated by Django 5.0.6 on 2024-06-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('price', models.IntegerField(db_default=10)),
                ('in_stock', models.BooleanField(db_default=True)),
            ],
        ),
    ]
