# Generated by Django 5.0.6 on 2024-06-25 07:02

from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_vector'),
    ]

    operations = [
        VectorExtension() # SQL: create extension "vector" -- requires "pgvector" package in db and superuser db role
    ]
