# Generated by Django 5.0.6 on 2024-06-25 08:13

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=512, editable=False, null=True),
        ),
    ]
